apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-broker
spec:
  selector:
    matchLabels:
      app: message-broker
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: message-broker
    spec:
      containers:
      - name: message-broker-pod
        image: strategies/activemq5-14-3
        #image: richardchesterwood/k8s-fleetman-queue:release1