apiVersion: v1
kind: Service

metadata:
  name: message-broker

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: message-broker

  ports:
  - name: http
    port: 8161
    nodePort: 30050

  - name: endpoint
    port: 61616

  type: NodePort